name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, pdo
          coverage: none

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: vendor/bin/phpunit tests
